### ISSUE TITLE
Artifacts folder

### ISSUE THREAD

**Issue by lucacome** [redhat-openshift-ecosystem/openshift-preflight#827] opened 2022-11-10 03:35 UTC
## Bug Description
Every time I run `preflight check container` I need to change the artifacts folder with `--artifacts=`.

```
Error: could not write file to artifacts directory: /tmp/artifacts/results.json already exists
```

## Version and Command Invocation
```
$ preflight --version
preflight version 1.4.2 <commit: f9cff772837132149df69f8ae251d3caf81c49ac>
```

## Steps to Reproduce:
(How can we reproduce this?)
1) Run `preflight check container` with an image
2) Run `preflight check container` with an image a second time
3) See the error `Error: could not write file to artifacts directory`

## Expected Result
The ideal would be for me to not have to specify the artifacts folder. I'm not even sure why that's needed.

## Actual Result
I have to change the folder in the command line for every architecture of every image that I want to certify.

**Comment by acornett21** [comment] 2022-11-10 14:42
Hi @lucacome This is working as designed, since we want to make sure the user clears out the artifacts folder for before each run to ensure we are using the latest information from the most recent run. Preflight by default writes to `./artifacts` by defaults so if you clean that folder each run this shouldn't be an issue.

Preflight uses this folder to save off information gathered in the checks/policies that are then later used during the submission process to send to the backend system.

**Comment by lucacome** [comment] 2022-11-11 01:00
Hi @acornett21 thanks for the explanation.

Maybe I'm missing some context, but I'm not sure how the artifacts folder is useful to the end user (like me).
Let's say I run `preflight check` and the outputs of the check are saved in `artifacts`. Then if I want to submit those results, since I don't have a specific command to do that without re-running the check, I just do `preflight check --submit` and get the error about the files already existing.
Another scenario is the one I described above about submitting multiple images/architectures (even without the two steps, just using the `--submit` flag right away). I would have to either change the folder name or delete it all together every time I run the command.

So in the end I'm not sure what benefit I'm getting from the artifacts folder (given that the `results.json` is also in the output of the command). Maybe I'm missing something and I'm supposed to use the files in the folder?

IMHO, a better experience (at least for me) is that if somebody uses `--artifacts string` means that they care about those files and should behave the same way it does today, but if they don't pass the flag it should default to a random folder in `/tmp`.

**Comment by komish** [comment] 2023-01-03 16:59
> This change is now creating support cases.

@jfrancin if able, could you describe/paraphrase what the support case's reported issue is, and what the recommended resolution is (most commonly)? I ask simply because it would seem the issue preflight detects, and its resolution should be derived from the error message it returns.

Are there more aspects of this issue leading to/warranting the support case that I'm not seeing other than "I need to clean out the artifacts directory and I didn't need to do so before"?

> You have changed the tool's behavior without the change being properly documented.

You're right. I generally supported this change _because_ it, in my opinion, led to less inconsistency. That is, working with a fresh directory, to me, is preferable.

---

For what it's worth: with some upcoming changes in our code's organization, we will see similar collision issues with the artifacts directory that we'll look to resolve that will likely also resolve this issue.

**Comment by komish** [comment] 2023-01-03 19:04
As a point of reference, I believe the issue is here: https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/174eea60db65c666cb29456ed22ea264f9cad6d0/certification/artifacts/artifacts.go#L55-L57

`SafeWriteReader` throws an error if the file already exists.

**Comment by acornett21** [comment] 2023-01-04 17:58
I just want to clear up a miss conception here, it's not _just_ the `results.json` file that gets written to `/artifacts`. The reason why the error is always for `results.json` is since preflight create this file 'early' in execution (one could argue even before execution preflight create this file) to ensure that preflight has write access to disk. preflight needs write access in the checks to write artifacts to disk for two reasons:

- To trouble shoot checks further, ie DeployableByOLM writes a Subscription file which usually has the failure reason.
- To take data from a check and use that data to submit to pyxis, ie `create container` we need to store the container/rpm info. 

So adding a timestamp wouldn't help, since we would not know which file to to pick for container/rpm/results. Having a clean/empty directory is ideal.

Like @komish mentioned, we are working on a large refactor that will hopefully also remove this pain point.

**Comment by komish** [comment] 2023-02-10 22:21
I believe with the merging of #866 that we can close this issue. Please re-open or create a new issue if there is anything further.

**Closed by komish** 2023-02-10 22:21 UTC
Labels: kind/bug
